FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Installation des dépendances
RUN pip install --no-cache-dir \
    mlflow==2.8.1 \
    psycopg2-binary \
    boto3 \
    pymysql

EXPOSE 5000

# Définition de la commande par défaut, qui sera remplacée dans docker-compose
CMD ["mlflow", "server", "--host", "0.0.0.0"]