# Use a Python base image
FROM base

WORKDIR /app

# Copier le code source
COPY src/webapp/ ./

ENV PYTHONPATH=/app

# Expose the Gradio default port
EXPOSE 7860

# Default command
CMD ["python", "/app/web.py"]