FROM base

WORKDIR /app

# Copier le code source
COPY src/api/ ./app/

# Exposer le port sur lequel l'API sera accessible
EXPOSE 8000

# Définir la commande de démarrage
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
