# 🌬️ Base officielle Airflow avec Python 3.8
FROM apache/airflow:2.7.1-python3.10

WORKDIR /opt/airflow

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt